### ISSUE TITLE
Jan 20 Tech Salon

### ISSUE THREAD

**Issue by danielglh** [strikingly/tech-salon#11]
## Topic: Monad in Swift

Speaker: Arthur Wang(@Arthraim), Strikingly iOS Developer

Summary: During the talk, Arthur will start from his learnings from  [@swift](http://atswift.io/) conference, including new trends, approaches and some personal new findings; after that he will be mainly talking his understanding of Monad in Swift.

**Comment by Arthraim** [comment]
I will start from what I've seen in [@swift](atswift.io), some new trending, new approaches and my personal new findings.
Then I will mainly talk about Monad in Swift.

**Comment by dfguo** [comment]
finished
