### ISSUE TITLE
Sept 2nd Tech Salon

### ISSUE THREAD

**Issue by dfguo** [strikingly/tech-salon#4]
We will have three topics this Wednesday night sharing.
### 暴走漫画数据挖掘从0到1

丁彦：暴走漫画数据挖掘总监

暴走漫画是国内在年轻人中颇具影响力的文化公司，产品包括社区，日报，游戏，视频。然而，随着暴漫用户的增长，运营的工作越来越重，也越来越需要照顾不同的用户。这时候数据服务团队应运而生。来到暴漫后，主要主导了 3 个方面的数据服务：搜索，推荐，反垃圾。这次主要和大家分享一点实践方面的经验，包括技术架构的选择，算法策略的选择等。
### GraphQL 101

Junchen: Strikingly Backend Engineer

GraphQL is the query language used by Relay, a new framework Facebook annouced early this year which provides data-fetching functionality for React applications. In this talk, Junchen will share the reason why GraphQL is exciting to both FE and BE, also the principles and basics of GraphQL.
### How to Give a Tech Sharing

Dafeng: Strikingly CTO

Tech sharing is a great way for developers to learn and share experience with each other. A good tech sharing ensures that the right message is received by the audience and creates a positive experience. A bad one doesn't deliver the right message and hurts speaker's credential and image. In this talk, Dafeng wants to share some of his experience doing a good tech sharing.

**Comment by onlimii** [comment]
GraphQL 101

Junchen: Strikingly Backend Engineer
GraphQL is the query language used by Relay, a new framework Facebook annouced early this year which provides data-fetching functionality for React applications. In this talk, Junchen will share the reason why GraphQL is exciting to both FE and BE, also the principles and basics of GraphQL.

**Comment by dfguo** [comment]
sharing is done. Thanks everyone for participating.
