### ISSUE TITLE
Sept 16 Tech Salon

### ISSUE THREAD

**Issue by dfguo** [strikingly/tech-salon#5]
Topics are yet to be confirmed.

**Comment by rechtar** [comment]
Inline Styles: What, Why and How

Jerry: Strikingly Frontend Engineer

Inline styles is a hot topic that's taking the React world by storm. In this sharing, Jerry will talk about why inline styles are brought to the discussion after sitting in the corner for years, what problems it's solving, and what we can do today to start enjoying its benefits without suffering from its share of problems.

**Comment by danielglh** [comment]
subject: 由点到面，提升公有云服务可用性

speaker: 林超，UCloud解决方案架构师

公有云越来越成为现在IT基础设施的首要选择，为了最大程度提高公有云的可用性，公有云商都做了哪些工作？本次分享会主要介绍UCloud在公有云上的的高可用实现，包括如何提升单点可用性，内核热补丁，IO加速，内存故障隔离，热迁移，容灾环网等特性。

**Comment by dfguo** [comment]
sharing is finished
