### ISSUE TITLE
Nov 11 Tech Salon

### ISSUE THREAD

**Issue by danielglh** [strikingly/tech-salon#8]
## Topic: Parsing Programming Language

Speaker: Glen Huang(@hgl), Strikingly Frontend Engineer

Summary: Brief introduction on parsing programming language, and also how to write a simple parser using a parser generator.
## Topic: HTML5 Compass

Speaker: 寸志(@island205)，陆金所前端架构师

Summary: 如何使用HTML5特性实现指南针和水平仪，就像iOS上的Compass应用那样。技术不是重点，主要是帮助大家复习物理和数学知识。

**Comment by Arthraim** [comment]
Video record of this time sharing: http://www.huajiao.com/live/share.php?liveid=2078185
